### PR TITLE
FINOPS-112 Use AWS Pricing API for AWS Unused IP Addresses

### PR DESCRIPTION
**Pull request by douglaswth**
### Description

- Improve savings calculations by using the AWS Pricing API which is significantly faster and more memory efficient than retrieving the AWS price sheet JSON file

### Issues Resolved

FINOPS-112

### Contribution Check List

- [x] All tests pass.
- [x] New functionality includes testing.
- [x] New functionality has been documented in the README if applicable
- [x] New functionality has been documented in CHANGELOG.MD

### CODE REVIEW

**Review by rshade — APPROVED** [review]
LGTM

**Review by rshade — APPROVED** [review]
LGTM

**Review by rshade — DISMISSED** [review]
LGTM

**Review by rshade — APPROVED** [review]
LGTM

**Comment by douglaswth** [comment]
@rshade I will hold off until Monday, February 7 to merge this.

**Pull request merged**
