### PR TITLE
HCLIND-4 Fix: Hardcoded TLD in cloud_cost_anomaly_alerts.pt to US

### PR DESCRIPTION
**Pull request by juanestrahcl**
### Description

Get dynamic TLD depending of current "rs_governance_host".

### Issues Resolved

Link to the report seems to be hardcoded to US shard.

### Contribution Check List

- [ ] All tests pass.
- [ ] New functionality includes testing.
- [x] New functionality has been documented in the README if applicable
- [x] New functionality has been documented in CHANGELOG.MD

### CODE REVIEW

**Review by lawrethao — CHANGES_REQUESTED** [review]
just needs an update of the version in the info block for the .pt file.

**Review by lawrethao — APPROVED** [review]
LGTM

**Comment by juanestrahcl** [comment]
Changes tested on [app.flexeratest.com](http://app.flexeratest.com/), I can’t test on [app.flexera.eu](http://app.flexera.eu/) because I don’t have access but I created a demo file to see if everything is working well.

**Review by lawrethao — APPROVED** [review]

**Review by lawrethao — APPROVED** [review]
LGTM

**Comment by degarajesh** [comment]
Test

**Comment by nia-vf1** [comment]
@juanestrahcl - what Jira ticket is this fix linked with? Please put reference to the Jira ticket in the name of this Pull Request e.g., 'POL-738 Fix: Hardcoded TLD in cloud_cost_anomaly_alerts.pt to US'

**Review by taniaSol — APPROVED** [review]

**Review by taniaSol — COMMENTED** [review]
Changes look good

**Review by taniaSol — APPROVED** [review]
Changes looking good

**Comment by juanestrahcl** [comment]
Closed since issue will be addressed here: [1161](https://github.com/flexera-public/policy_templates/pull/1161).

**Pull request closed without merging**
