### PR TITLE
POL-787 Update PT to use Flexera One APIs

### PR DESCRIPTION
**Pull request by bryankaraffa**
### Description

Example Applied Policy:
https://app.flexera.com/orgs/28010/automation/applied-policies/projects/123559?policyId=642362caff3f0400013d1e73&noIndex=1

Update Scheduled FlexNet Manager Report to use Flexera One API endpoints and authentication.

Full details for related change https://community.flexera.com/t5/Flexera-One-Blog/Flexera-One-ITAM-SOAP-APIs-Transitioning-to-Flexera-One-IAM/ba-p/229399

### Issues Resolved

https://flexera.atlassian.net/browse/POL-787

### Contribution Check List

- [x] All tests pass.
- [X] New functionality has been documented in the README if applicable
- [X] New functionality has been documented in CHANGELOG.MD

### CODE REVIEW

**Review by taterdog590 — APPROVED** [review]
LGTM

**Comment by JDFlex** [comment]
In the README, it references a Flexera Credential having a "role" of flexera_fnms.  What is that?  Should that be "flexera" or "oauth2" or "auth_flexera"?  Or is this something completely different?  Everything else in this PR looks good to me.

**Comment by bryankaraffa** [comment]
> In the README, it references a Flexera Credential having a "role" of flexera_fnms. What is that? Should that be "flexera" or "oauth2" or "auth_flexera"? Or is this talking about Flexera One IAM roles? If Flexera One IAM roles, would that be the role called "View IT assets & call APIs"? In addition to having that role, the account tied to that credential must also have proper permissions configured under IT Asset Accounts, giving permissions to run reports in ITAM (FNMS). Everything else in this PR looks good to me.

Updated the role name in README to include API name and the label in the UI view -- it was incorrect already as `flexera_fnms` so this is a fix for the current README

**Review by JDFlex — COMMENTED** [review]
Just one comment about the required role

**Review by taterdog590 — APPROVED** [review]
LGTM

**Review by taterdog590 — APPROVED** [review]

**Pull request merged**
