### PR TITLE
feat: Meta Parent Policy Template compiler

### PR DESCRIPTION
**Pull request by bryankaraffa**
### Description

Eliminates need to manually create/maintain the Meta Parent Policy Templates

Normalizes implementation of the Meta Parent Policies (field names, labels, etc..)

### Link to Example Applied Policy

Example updated Meta Parent Policies that have been compiled with script and applied:
- https://app.flexera.com/orgs/27018/automation/applied-policies/projects/116186?policyId=64a63eb7ece4e60001bb0bf8
- https://app.flexera.com/orgs/27018/automation/applied-policies/projects/116186?policyId=64a63e69807aa90001aad548
- https://app.flexera.com/orgs/27018/automation/applied-policies/projects/116186?policyId=64a60f51807aa90001aad13d
- https://app.flexera.com/orgs/27018/automation/applied-policies/projects/116186?policyId=64a60f14ece4e60001bb085a
- https://app.flexera.com/orgs/27018/automation/applied-policies/projects/116186?policyId=64a60c1eece4e60001bb07a9
- https://app.flexera.com/orgs/27018/automation/applied-policies/projects/116186?policyId=64a60bc9ece4e60001bb0796
(( expect that meta parent incidents are functionally the same as before ))

### Contribution Check List

- [X] New functionality has been documented in the README if applicable
- [X] New functionality has been documented in CHANGELOG.MD

### CODE REVIEW

**Review by XOmniverse — APPROVED** [review]
LGTM. Good work! :)

**Comment by bryankaraffa** [comment]
> ## Danger has errored
> 
> [!] Invalid `Dangerfile` file: bad URI(is not URI?): https//githubcom/flexera-public/policy_templates/actions/workflows/generate-meta-parent-policy-templatesyaml/badgesvgevent=push]https//githubcom/flexera-public/policy_templates/actions/workflows/generate-meta-parent-policy-templatesyaml. Updating the Danger gem might fix the issue. Your Danger version: 8.4.2, latest Danger version: 9.3.1
> 
> ```
>  #  from Dangerfile:66
>  #  -------------------------------------------
>  #           url_string = url.to_s.gsub(/[!@#$%^&*(),.?":{}|<>]/,'')  #remove extra chars
>  >           url = URI(url_string) #convert to URL
>  #           # check for a valid host.  skip urls that are dynamicly constructed may not have a valid hostname
>  #  -------------------------------------------
> ```
> 
> Generated by 🚫 [Danger](https://danger.systems/)

Ignoring this error.. it's a false positive on the GitHub Actions status icon badge.  Can fix/enhance Dangerfile with another PR.. but should only fail again if we modify the README.md [3bfe34c](https://github.com/flexera-public/policy_templates/pull/1344/commits/3bfe34c0e3de8b5ff9c738102634e75ab0eb2487)

**Review by XOmniverse — APPROVED** [review]
LGTM

**Review by XOmniverse — COMMENTED** [review]
LGTM

**Pull request merged**
